blank_issues_enabled: false
contact_links:
  - name: ❓ Support
    url: https://github.com/net-lisias-ksp/TweakScale/discussions/categories/support
    about: For getting help about something wrong. **Always** tag me using @Lisias or I may take too long to respond!
